config/routes.rb
Rails.application.routes.draw do
  root 'home#coordinate'
  get 'home/sneaker'
  get 'home/hairarrange'
  get 'home/nail'
  get 'home/makeup'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def coordinate
    #タグからひっぱてくる
    @coordinate = Instagram.tag_recent_media(URI.encode("コーデ"), {:count => 50})
  end

  def sneaker
    #タグからひっぱてくる
    @sneaker = Instagram.tag_recent_media(URI.encode("スニーカー"), {:count => 50})
  end

  def hairarrange
    #タグからひっぱてくる
    @hairarrange = Instagram.tag_recent_media(URI.encode("hairarrange"), {:count => 50})
  end

  def nail
    #タグからひっぱてくる
    @nail = Instagram.tag_recent_media(URI.encode("ネイル"), {:count => 50})
  end

  def makeup
    #タグからひっぱてくる
    @makeup = Instagram.tag_recent_media(URI.encode("メイク"), {:count => 50})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/coordinate.html.erb
<h1>Coordinate</h1>

<% @coordinate.each do |coordinate| %>
  <%= link_to coordinate.link, :target => "_blank" do %>
    <%= image_tag(coordinate.images.low_resolution.url) %>
  <% end %>
<% end %>

app/views/home/hairarrange.html.erb
<h1>HairArrange</h1>

<% @hairarrange.each do |hairarrange| %>
  <%= link_to hairarrange.link, :target => "_blank" do %>
    <%= image_tag(hairarrange.images.low_resolution.url) %>
  <% end %>
<% end %>

app/views/home/makeup.html.erb
<h1>Makeup</h1>

<% @makeup.each do |makeup| %>
  <%= link_to makeup.link, :target => "_blank" do %>
    <%= image_tag(makeup.images.low_resolution.url) %>
  <% end %>
<% end %>

app/views/home/nail.html.erb
<h1>Nail</h1>

<% @nail.each do |nail| %>
  <%= link_to nail.link, :target => "_blank" do %>
    <%= image_tag(nail.images.low_resolution.url) %>
  <% end %>
<% end %>

app/views/home/sneaker.html.erb
<h1>Sneaker</h1>

<% @sneaker.each do |sneaker| %>
  <%= link_to sneaker.link, :target => "_blank" do %>
    <%= image_tag(sneaker.images.low_resolution.url) %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FashionGirl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div="container">

<div class="btn-group btn-group-justified">
  <%= link_to 'コーデ', root_path, class: :"btn btn-warning" %>
  <%= link_to 'スニーカー', home_sneaker_path, class: :"btn btn-primary" %>
  <%= link_to 'ヘアアレンジ', home_hairarrange_path, class: :"btn btn-success" %>
  <%= link_to 'ネイル', home_nail_path, class: :"btn btn-info" %>
  <%= link_to 'メイク', home_makeup_path, class: :"btn btn-danger" %>
</div>

<%= yield %>
</div>
</body>
</html>